import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const BASE_MANIFEST = JSON.parse(readFileSync(join(ROOT, 'manifest.base.json'), 'utf8'));

function sourceFiles(directory) {
  const files = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...sourceFiles(path));
    else if (entry.isFile() && path.endsWith('.js')) files.push(path);
  }
  return files;
}

function manifestScripts(manifest) {
  const scripts = [];
  for (const entry of manifest.content_scripts || []) scripts.push(...(entry.js || []));
  if (manifest.background?.service_worker) scripts.push(manifest.background.service_worker);
  scripts.push(...(manifest.background?.scripts || []));
  return scripts;
}

/**
 * Top-level `const`/`let`/`class`/`function` names of a classic script,
 * including names bound by a top-level object-destructuring declaration.
 */
function topLevelDeclarations(source) {
  const lines = source.split('\n');
  const names = [];

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const declaration = /^(?:const|let|var|class|function)\s+([A-Za-z0-9_$]+)/.exec(line);
    if (declaration) {
      names.push(declaration[1]);
      continue;
    }

    if (!/^(?:const|let|var)\s*\{/.test(line)) continue;
    let block = '';
    for (let end = index; end < lines.length; end += 1) {
      block += lines[end];
      if (lines[end].includes('}')) {
        index = end;
        break;
      }
    }
    const bindings = block.slice(block.indexOf('{') + 1, block.indexOf('}'));
    for (const binding of bindings.split(',')) {
      const name = binding.split(':').pop().trim();
      if (name) names.push(name);
    }
  }

  return names;
}

function popupScripts() {
  const html = readFileSync(join(SRC, 'popup/popup.html'), 'utf8');
  return [...html.matchAll(/<script src="([^"]+)"><\/script>/g)]
    .map((match) => join('src/popup', match[1]));
}

// Every file of a content script (and of the popup page) shares one global
// lexical scope, so a name declared twice is a load-time SyntaxError.
test('co-loaded scripts declare unique top-level identifiers', () => {
  const bundles = {
    content: manifestScripts({ content_scripts: BASE_MANIFEST.content_scripts }),
    popup: popupScripts()
  };

  for (const [bundle, files] of Object.entries(bundles)) {
    const owners = new Map();
    for (const file of files) {
      for (const name of topLevelDeclarations(readFileSync(join(ROOT, file), 'utf8'))) {
        assert.equal(owners.get(name), undefined, `${bundle}: "${name}" declared in ${owners.get(name)} and ${file}`);
        owners.set(name, file);
      }
    }
  }
});

test('source tree has no generated bundle or ES module syntax', () => {
  const files = sourceFiles(SRC);
  assert.ok(!files.some((file) => file.endsWith('content.bundle.js')));

  for (const file of files) {
    const source = readFileSync(file, 'utf8');
    assert.doesNotMatch(source, /^\s*(import|export)\b/m, relative(ROOT, file));
    assert.doesNotMatch(source, /GENERATED by scripts\/bundle-content/);
  }
});

test('base manifest loads direct source files only', () => {
  const scripts = manifestScripts(BASE_MANIFEST);
  assert.ok(scripts.length > 0);
  assert.ok(!scripts.some((file) => file.includes('content.bundle.js')));
  for (const file of scripts) assert.ok(existsSync(join(ROOT, file)), file);
});

test('browser builds copy source files unchanged', () => {
  for (const browser of ['chrome', 'firefox']) {
    const manifestPath = join(ROOT, 'dist', browser, 'manifest.json');
    assert.ok(existsSync(manifestPath), `missing ${browser} build`);
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    for (const file of manifestScripts(manifest)) {
      const sourcePath = join(ROOT, file);
      const distPath = join(ROOT, 'dist', browser, file);
      assert.equal(readFileSync(distPath, 'utf8'), readFileSync(sourcePath, 'utf8'), `${browser}/${file}`);
    }
  }
});

test('generated manifests preserve browser-specific interceptor behavior', () => {
  const chrome = JSON.parse(readFileSync(join(ROOT, 'dist/chrome/manifest.json'), 'utf8'));
  const firefox = JSON.parse(readFileSync(join(ROOT, 'dist/firefox/manifest.json'), 'utf8'));
  assert.equal(chrome.background.type, 'module');
  assert.ok(chrome.content_scripts.some((entry) => entry.world === 'MAIN'));
  assert.ok(!firefox.content_scripts.some((entry) => entry.world === 'MAIN'));
  assert.ok(firefox.browser_specific_settings.gecko.id);
});
